### PR TITLE
Knutel/new dromajo patch

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Soooo.... this PR contains the latest master + Dromajo patch updates to make your fork/branch work.  Let's see what happens. 😆

**Comment by ghost** [comment]
@light2802 are you still working with this project?  If so, can you commit my patch into yours (and hence into Olympia)?  If not, I'll go ahead and close this PR and the PR in Olympia and put up my patch as a combo to yours.

**Comment by light2802** [comment]
Sure can you tell how to commit your patch into mine :)

**Comment by ghost** [comment]
image
As you can see, I can't merge this PR into your branch -- I think only you can do that.

**Comment by light2802** [comment]
I can see option to merge in to the base branch

**Comment by ghost** [comment]
Yep.  Please push it.  😄

**Comment by light2802** [comment]
Done

**Pull request merged**
